# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='uname',
            field=models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_uname', to='db.User'),
        ),
    ]
