# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ufile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
