# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20161206_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uphoto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
