# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20161210_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportphoto',
            name='rp_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='rw_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
