# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20161210_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyWordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='keyword_uname', to='db.User')),
            ],
            options={
                'db_table': 'user_keyword_history',
            },
        ),
        migrations.CreateModel(
            name='UserRecipeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_rid', to='db.Recipe')),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_uname', to='db.User')),
            ],
            options={
                'db_table': 'user_recipe_history',
            },
        ),
        migrations.CreateModel(
            name='UserTagHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.ForeignKey(db_column='tname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_rid', to='db.Tag')),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_uname', to='db.User')),
            ],
            options={
                'db_table': 'user_tag_history',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='rwcontext',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='suggestion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usertaghistory',
            unique_together=set([('uname', 'tname')]),
        ),
        migrations.AlterUniqueTogether(
            name='userrecipehistory',
            unique_together=set([('uname', 'rid')]),
        ),
        migrations.AlterUniqueTogether(
            name='userkeywordhistory',
            unique_together=set([('uname', 'keyword')]),
        ),
    ]
