# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_recipe_rtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rphoto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
