# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_conver'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyWordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='keyword_uname', to='group.User')),
            ],
            options={
                'db_table': 'user_keyword_history',
            },
        ),
        migrations.CreateModel(
            name='UserRecipeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_rid', to='group.Recipe')),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_uname', to='group.User')),
            ],
            options={
                'db_table': 'user_recipe_history',
            },
        ),
        migrations.CreateModel(
            name='UserTagHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_uname', to='group.User')),
            ],
            options={
                'db_table': 'user_tag_history',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usertaghistory',
            unique_together=set([('uname', 'tname')]),
        ),
        migrations.AlterUniqueTogether(
            name='userrecipehistory',
            unique_together=set([('uname', 'rid')]),
        ),
        migrations.AlterUniqueTogether(
            name='userkeywordhistory',
            unique_together=set([('uname', 'keyword')]),
        ),
    ]
