# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20161211_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkeywordhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userrecipehistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usertaghistory',
            options={'managed': False},
        ),
    ]
